org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

mod_version=0.2.6
maven_group=me.bluejay

fabric_api_version=0.116.11+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0